alias iconf='nvim ~/.config/i3/config'
alias aliases='nvim ~/.bash_aliases'
alias vim='nvim'
alias polyconf='vim ~/.config/i3/polybar.conf'
alias vimconf='cd ~/.config/nvim/'
alias pi='python3'
alias py='python3'
alias wallpaper='~/.local/share/wallpaper'
